/* =====================================================================
   MERIDIAN LIFE — 62_pptx_procedure.sql
   TOOL 10 — generate_pptx_report

   Builds a branded Meridian Life PowerPoint from live Snowflake data and
   returns a single-cell JSON array containing a PRESIGNED URL the end user
   can click straight from the chat answer.

   Runs as an owner's-rights Snowpark Python procedure so the caller does
   not need direct grants on the underlying tables or the stage.
   ===================================================================== */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE GEN2_SMALL;
USE SCHEMA INSURANCE_DEMO.CORE;

CREATE OR REPLACE PROCEDURE GENERATE_PPTX_REPORT(
    P_TITLE     VARCHAR,
    P_BRANCH_ID VARCHAR
)
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python', 'python-pptx')
HANDLER = 'main'
COMMENT = 'Generate a branded Meridian Life PPTX executive report and return a presigned download URL as single-cell JSON.'
EXECUTE AS OWNER
AS
$$
import json
import re
import uuid
from datetime import datetime

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

TEAL = RGBColor(0x0E, 0x5C, 0x63)
GOLD = RGBColor(0xD4, 0xA0, 0x3C)
GREY = RGBColor(0x4A, 0x55, 0x68)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
STAGE = "@INSURANCE_DEMO.CORE.STAGE_EXPORT"


def rp(v):
    """Format a number as Indonesian Rupiah in billions/millions."""
    if v is None:
        return "n/a"
    v = float(v)
    if abs(v) >= 1e9:
        return f"Rp {v/1e9:,.2f} B"
    if abs(v) >= 1e6:
        return f"Rp {v/1e6:,.1f} M"
    return f"Rp {v:,.0f}"


def _txbox(slide, x, y, w, h, text, size, color, bold=False, align=PP_ALIGN.LEFT):
    box = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    r = p.add_run()
    r.text = text
    r.font.size = Pt(size)
    r.font.bold = bold
    r.font.color.rgb = color
    r.font.name = "Calibri"
    return box


def _band(slide, prs, height_in=1.15):
    bar = slide.shapes.add_shape(1, Inches(0), Inches(0), prs.slide_width, Inches(height_in))
    bar.fill.solid()
    bar.fill.fore_color.rgb = TEAL
    bar.line.fill.background()
    bar.shadow.inherit = False
    return bar


def _title_slide(prs, title, subtitle):
    s = prs.slides.add_slide(prs.slide_layouts[6])
    bg = s.shapes.add_shape(1, Inches(0), Inches(0), prs.slide_width, prs.slide_height)
    bg.fill.solid()
    bg.fill.fore_color.rgb = TEAL
    bg.line.fill.background()
    bg.shadow.inherit = False
    _txbox(s, 0.8, 2.0, 11.5, 0.5, "MERIDIAN LIFE", 16, GOLD, True)
    _txbox(s, 0.8, 2.6, 11.5, 1.2, title, 40, WHITE, True)
    _txbox(s, 0.8, 4.0, 11.5, 0.6, subtitle, 16, WHITE)
    _txbox(s, 0.8, 6.6, 11.5, 0.4,
           "Fictional company. Synthetic data. Generated by Cortex Agent.", 10, WHITE)
    return s


def _kpi_slide(prs, kpis):
    s = prs.slides.add_slide(prs.slide_layouts[6])
    _band(s, prs)
    _txbox(s, 0.6, 0.28, 10, 0.6, "Company Performance 2025", 26, WHITE, True)
    x, y = 0.6, 1.7
    for i, (label, value) in enumerate(kpis):
        if i and i % 3 == 0:
            x, y = 0.6, y + 2.0
        card = s.shapes.add_shape(1, Inches(x), Inches(y), Inches(3.9), Inches(1.7))
        card.fill.solid()
        card.fill.fore_color.rgb = RGBColor(0xF2, 0xF6, 0xF7)
        card.line.color.rgb = TEAL
        card.shadow.inherit = False
        _txbox(s, x + 0.25, y + 0.22, 3.4, 0.4, label, 11, GREY, True)
        _txbox(s, x + 0.25, y + 0.68, 3.4, 0.8, value, 24, TEAL, True)
        x += 4.15
    return s


def _table_slide(prs, heading, headers, rows, widths=None):
    s = prs.slides.add_slide(prs.slide_layouts[6])
    _band(s, prs)
    _txbox(s, 0.6, 0.28, 11, 0.6, heading, 24, WHITE, True)
    nrows, ncols = len(rows) + 1, len(headers)
    shape = s.shapes.add_table(nrows, ncols, Inches(0.5), Inches(1.5),
                               Inches(12.3), Inches(0.32 * nrows))
    tbl = shape.table
    if widths:
        total = sum(widths)
        for i, w in enumerate(widths):
            tbl.columns[i].width = Inches(12.3 * w / total)
    for c, h in enumerate(headers):
        cell = tbl.cell(0, c)
        cell.text = str(h)
        para = cell.text_frame.paragraphs[0]
        para.runs[0].font.size = Pt(11)
        para.runs[0].font.bold = True
        para.runs[0].font.color.rgb = WHITE
        cell.fill.solid()
        cell.fill.fore_color.rgb = TEAL
    for r, row in enumerate(rows, start=1):
        for c, val in enumerate(row):
            cell = tbl.cell(r, c)
            cell.text = "" if val is None else str(val)
            para = cell.text_frame.paragraphs[0]
            if para.runs:
                para.runs[0].font.size = Pt(10)
                para.runs[0].font.color.rgb = GREY
            cell.fill.solid()
            cell.fill.fore_color.rgb = WHITE if r % 2 else RGBColor(0xF2, 0xF6, 0xF7)
    return s


def main(session, p_title, p_branch_id):
    title = (p_title or "Sales Command Center Report").strip()
    branch = (p_branch_id or "").strip()
    bfilter = ""
    if branch:
        safe = branch.replace("'", "''")
        bfilter = f" AND (BRANCH_ID = '{safe}' OR BRANCH_NAME ILIKE '%{safe}%')"

    # ---- company KPIs -------------------------------------------------
    k = session.sql("""
        SELECT TOTAL_FYAP, TARGET_FYAP, ACHIEVEMENT_PCT, NEW_POLICIES,
               ACTIVE_AGENTS, PERSISTENCY_13M_PCT, LOSS_RATIO_PCT
        FROM INSURANCE_DEMO.CORE.V_DASHBOARD_KPIS WHERE FISCAL_YEAR = 2025
    """).collect()[0]
    risk = session.sql("""
        SELECT COUNT_IF(RISK_SEGMENT IN ('HIGH','CRITICAL')) AS N,
               SUM(IFF(RISK_SEGMENT IN ('HIGH','CRITICAL'), ANNUAL_PREMIUM, 0)) AS V
        FROM INSURANCE_DEMO.CORE.LAPSE_RISK_SCORES
    """).collect()[0]
    pipe = session.sql("""
        SELECT COUNT(*) AS N, SUM(EXPECTED_VALUE) AS V
        FROM INSURANCE_DEMO.CORE.AI_RECOMMENDATIONS WHERE STATUS = 'OPEN'
    """).collect()[0]

    kpis = [
        ("2025 FYAP (actual)", rp(k["TOTAL_FYAP"])),
        ("2025 Plan", rp(k["TARGET_FYAP"])),
        ("Achievement", f"{k['ACHIEVEMENT_PCT']:.1f}%" if k["ACHIEVEMENT_PCT"] else "n/a"),
        ("New policies", f"{k['NEW_POLICIES']:,}"),
        ("13-month persistency",
         f"{k['PERSISTENCY_13M_PCT']:.1f}%" if k["PERSISTENCY_13M_PCT"] else "n/a"),
        ("Loss ratio", f"{k['LOSS_RATIO_PCT']:.1f}%" if k["LOSS_RATIO_PCT"] else "n/a"),
        ("High-risk policies", f"{risk['N']:,}"),
        ("Premium at risk", rp(risk["V"])),
        ("Open action pipeline", f"{pipe['N']:,} / {rp(pipe['V'])}"),
    ]

    ach = session.sql(f"""
        SELECT BRANCH_NAME, PROVINCE, TARGET_FYAP, ACTUAL_FYAP, ACHIEVEMENT_PCT, ACHIEVEMENT_BAND
        FROM INSURANCE_DEMO.CORE.V_BRANCH_ACHIEVEMENT
        WHERE FISCAL_YEAR = 2025 {bfilter}
        ORDER BY ACHIEVEMENT_PCT ASC LIMIT 12
    """).collect()
    acts = session.sql(f"""
        SELECT RECOMMENDATION_TYPE, PRIORITY, URGENCY_SCORE,
               COALESCE(AGENT_NAME, '(branch)') AS OWNER, BRANCH_NAME, TITLE, EXPECTED_VALUE
        FROM INSURANCE_DEMO.CORE.AI_RECOMMENDATIONS
        WHERE STATUS = 'OPEN' {bfilter}
        ORDER BY URGENCY_SCORE DESC LIMIT 12
    """).collect()

    # ---- build the deck ----------------------------------------------
    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(13.333), Inches(7.5)
    scope = f"Branch: {branch}" if branch else "All 23 branches"
    _title_slide(prs, title,
                 f"{scope}  |  Fiscal year 2025  |  Generated {datetime.utcnow():%d %b %Y %H:%M} UTC")
    _kpi_slide(prs, kpis)
    _table_slide(
        prs, "Branch Achievement vs Plan (lowest first)",
        ["Branch", "Province", "Plan", "Actual", "Ach %", "Band"],
        [[r["BRANCH_NAME"], r["PROVINCE"], rp(r["TARGET_FYAP"]), rp(r["ACTUAL_FYAP"]),
          f"{r['ACHIEVEMENT_PCT']:.1f}%", r["ACHIEVEMENT_BAND"]] for r in ach],
        widths=[2.6, 2.0, 1.7, 1.7, 1.0, 1.8])
    _table_slide(
        prs, "Priority Action Queue (by urgency)",
        ["Type", "Pri", "Urg", "Owner", "Branch", "Action", "Value"],
        [[r["RECOMMENDATION_TYPE"], r["PRIORITY"], f"{r['URGENCY_SCORE']:.0f}",
          r["OWNER"], r["BRANCH_NAME"], (r["TITLE"] or "")[:58], rp(r["EXPECTED_VALUE"])]
         for r in acts],
        widths=[2.2, 0.7, 0.6, 1.9, 1.6, 4.2, 1.4])

    # ---- write to stage and presign ----------------------------------
    slug = re.sub(r"[^A-Za-z0-9]+", "_", (branch or "AllBranches")).strip("_")
    fname = f"MeridianLife_{slug}_{datetime.utcnow():%Y%m%d%H%M%S}_{uuid.uuid4().hex[:6]}.pptx"
    local = f"/tmp/{fname}"
    prs.save(local)
    session.file.put(local, STAGE, auto_compress=False, overwrite=True)

    url = session.sql(
        f"SELECT GET_PRESIGNED_URL('{STAGE}', '{fname}', 86400) AS URL"
    ).collect()[0]["URL"]

    return json.dumps([{
        "RESULT": "GENERATED",
        "FILE_NAME": fname,
        "SLIDES": len(prs.slides.__iter__.__self__._sldIdLst),
        "SCOPE": scope,
        "DOWNLOAD_URL": url,
        "URL_EXPIRES_IN_HOURS": 24,
    }])
$$;

/* ---- Smoke test ------------------------------------------------------ */
CALL GENERATE_PPTX_REPORT('Q4 2025 Sales Command Center Review', 'Jember');
