/* =====================================================================
   MERIDIAN LIFE — 81_closed_loop.sql
   Closed loop: Command Center -> Leaders -> Agents -> Outcome -> Dashboard
   ===================================================================== */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE GEN2_SMALL;
USE SCHEMA INSURANCE_DEMO.CORE;

CREATE OR REPLACE TABLE RECOMMENDATION_FEEDBACK (
    FEEDBACK_ID        VARCHAR(40),
    RECOMMENDATION_ID  VARCHAR(40),
    SUBMITTED_AT       TIMESTAMP_NTZ,
    SUBMITTED_BY_ROLE  VARCHAR(30),
    SUBMITTED_BY_NAME  VARCHAR(80),
    DECISION           VARCHAR(20),
    USEFULNESS_RATING  NUMBER(2,0),
    REJECT_REASON      VARCHAR(60),
    COMMENTS           VARCHAR(500)
);

CREATE OR REPLACE TABLE RECOMMENDATION_OUTCOME (
    OUTCOME_ID         VARCHAR(40),
    RECOMMENDATION_ID  VARCHAR(40),
    RECORDED_AT        TIMESTAMP_NTZ,
    ACTION_TAKEN       VARCHAR(60),
    CONTACT_ATTEMPTS   NUMBER(3,0),
    OUTCOME_STATUS     VARCHAR(30),
    REALISED_VALUE     NUMBER(20,2),
    DAYS_TO_OUTCOME    NUMBER(4,0),
    NOTES              VARCHAR(500)
);

-- Seed ~35% of the queue with synthetic feedback + outcomes
INSERT INTO RECOMMENDATION_FEEDBACK
WITH pick AS (
    SELECT r.RECOMMENDATION_ID, r.RECOMMENDATION_TYPE, r.AGENT_NAME, r.BRANCH_NAME,
           r.URGENCY_SCORE, r.EXPECTED_VALUE
    FROM AI_RECOMMENDATIONS r
    WHERE RND(r.RECOMMENDATION_ID, 2000) < 0.35
)
SELECT
    'FB-' || RIGHT(RECOMMENDATION_ID, 24),
    RECOMMENDATION_ID,
    DATEADD(day, RNDI(RECOMMENDATION_ID, 2001, 1, 25), '2025-12-01'::TIMESTAMP_NTZ),
    CASE WHEN RECOMMENDATION_TYPE = 'BRANCH_BELOW_TARGET' THEN 'HEAD_OFFICE'
         WHEN RECOMMENDATION_TYPE IN ('COACHING_ACTIVITY','REACTIVATION') THEN 'BRANCH_LEADER'
         ELSE 'AGENT' END,
    COALESCE(AGENT_NAME, BRANCH_NAME || ' Leader'),
    CASE WHEN RND(RECOMMENDATION_ID, 2002) < (0.45 + 0.004 * URGENCY_SCORE) THEN 'ACCEPTED'
         WHEN RND(RECOMMENDATION_ID, 2002) < (0.72 + 0.004 * URGENCY_SCORE) THEN 'DEFERRED'
         ELSE 'REJECTED' END,
    RNDI(RECOMMENDATION_ID, 2003, 2, 5),
    CASE WHEN RND(RECOMMENDATION_ID, 2002) >= (0.72 + 0.004 * URGENCY_SCORE)
         THEN ARRAY_CONSTRUCT('Customer already contacted','Wrong contact details',
                              'Customer not reachable','Not the right timing',
                              'Already surrendered','Agent no longer servicing')[RNDI(RECOMMENDATION_ID,2004,0,5)]::VARCHAR
    END,
    NULL
FROM pick;

INSERT INTO RECOMMENDATION_OUTCOME
WITH acc AS (
    SELECT f.RECOMMENDATION_ID, f.SUBMITTED_AT, r.RECOMMENDATION_TYPE,
           r.EXPECTED_VALUE, r.URGENCY_SCORE
    FROM RECOMMENDATION_FEEDBACK f
    JOIN AI_RECOMMENDATIONS r ON r.RECOMMENDATION_ID = f.RECOMMENDATION_ID
    WHERE f.DECISION = 'ACCEPTED'
)
SELECT
    'OC-' || RIGHT(RECOMMENDATION_ID, 24),
    RECOMMENDATION_ID,
    DATEADD(day, RNDI(RECOMMENDATION_ID, 2010, 2, 30), SUBMITTED_AT),
    CASE RECOMMENDATION_TYPE
      WHEN 'RETENTION_CALL'      THEN ARRAY_CONSTRUCT('Called','WhatsApp','Home visit')[RNDI(RECOMMENDATION_ID,2011,0,2)]::VARCHAR
      WHEN 'RENEWAL_FOLLOW_UP'   THEN ARRAY_CONSTRUCT('Called','WhatsApp','Auto-debit set up')[RNDI(RECOMMENDATION_ID,2011,0,2)]::VARCHAR
      WHEN 'CROSS_SELL'          THEN ARRAY_CONSTRUCT('Proposal sent','Illustration shown','Client meeting')[RNDI(RECOMMENDATION_ID,2011,0,2)]::VARCHAR
      WHEN 'COACHING_ACTIVITY'   THEN 'Coaching session held'
      WHEN 'REACTIVATION'        THEN 'Re-engagement call'
      ELSE 'Branch review meeting' END,
    RNDI(RECOMMENDATION_ID, 2012, 1, 4),
    CASE
      WHEN RECOMMENDATION_TYPE IN ('RETENTION_CALL','RENEWAL_FOLLOW_UP') THEN
        CASE WHEN RND(RECOMMENDATION_ID, 2013) < 0.62 THEN 'RETAINED'
             WHEN RND(RECOMMENDATION_ID, 2013) < 0.82 THEN 'LAPSED_ANYWAY'
             WHEN RND(RECOMMENDATION_ID, 2013) < 0.93 THEN 'IN_PROGRESS'
             ELSE 'NO_CONTACT' END
      WHEN RECOMMENDATION_TYPE = 'CROSS_SELL' THEN
        CASE WHEN RND(RECOMMENDATION_ID, 2013) < 0.28 THEN 'SOLD'
             WHEN RND(RECOMMENDATION_ID, 2013) < 0.66 THEN 'DECLINED'
             ELSE 'IN_PROGRESS' END
      ELSE
        CASE WHEN RND(RECOMMENDATION_ID, 2013) < 0.70 THEN 'IN_PROGRESS'
             ELSE 'RETAINED' END
    END,
    0, RNDI(RECOMMENDATION_ID, 2014, 2, 45), NULL
FROM acc;

UPDATE RECOMMENDATION_OUTCOME o
SET REALISED_VALUE = CASE
        WHEN o.OUTCOME_STATUS = 'RETAINED' THEN ROUND(r.EXPECTED_VALUE * (0.85 + 0.30 * RND(o.RECOMMENDATION_ID, 2020)), 2)
        WHEN o.OUTCOME_STATUS = 'SOLD'     THEN ROUND(r.EXPECTED_VALUE * (0.70 + 0.60 * RND(o.RECOMMENDATION_ID, 2021)), 2)
        ELSE 0 END
FROM AI_RECOMMENDATIONS r
WHERE r.RECOMMENDATION_ID = o.RECOMMENDATION_ID;

UPDATE AI_RECOMMENDATIONS r SET STATUS = CASE WHEN o.OUTCOME_STATUS = 'IN_PROGRESS' THEN 'IN_PROGRESS' ELSE 'DONE' END
FROM RECOMMENDATION_OUTCOME o WHERE o.RECOMMENDATION_ID = r.RECOMMENDATION_ID;

UPDATE AI_RECOMMENDATIONS r SET STATUS = 'DISMISSED'
FROM RECOMMENDATION_FEEDBACK f
WHERE f.RECOMMENDATION_ID = r.RECOMMENDATION_ID AND f.DECISION = 'REJECTED' AND r.STATUS = 'OPEN';

CREATE OR REPLACE VIEW V_RECOMMENDATION_LOOP AS
SELECT r.*, f.DECISION, f.USEFULNESS_RATING, f.SUBMITTED_BY_ROLE, f.SUBMITTED_AT AS FEEDBACK_AT,
       o.ACTION_TAKEN, o.OUTCOME_STATUS, o.REALISED_VALUE, o.DAYS_TO_OUTCOME, o.CONTACT_ATTEMPTS,
       CASE WHEN o.OUTCOME_STATUS IN ('RETAINED','SOLD')  THEN 'WIN'
            WHEN o.OUTCOME_STATUS IN ('LAPSED_ANYWAY','DECLINED','NO_CONTACT') THEN 'LOSS'
            WHEN o.OUTCOME_STATUS = 'IN_PROGRESS'          THEN 'PENDING'
            WHEN f.DECISION = 'REJECTED'                   THEN 'NOT_ACTIONED'
            WHEN f.DECISION IS NULL                        THEN 'AWAITING_FEEDBACK'
            ELSE 'PENDING' END AS LOOP_STAGE
FROM AI_RECOMMENDATIONS r
LEFT JOIN RECOMMENDATION_FEEDBACK f ON f.RECOMMENDATION_ID = r.RECOMMENDATION_ID
LEFT JOIN RECOMMENDATION_OUTCOME  o ON o.RECOMMENDATION_ID = r.RECOMMENDATION_ID;

CREATE OR REPLACE VIEW V_MODEL_EFFECTIVENESS AS
SELECT RECOMMENDATION_TYPE, SIGNAL_SOURCE, COUNT(*) TOTAL_RECOMMENDED,
       COUNT_IF(DECISION IS NOT NULL) WITH_FEEDBACK,
       COUNT_IF(DECISION = 'ACCEPTED') ACCEPTED,
       ROUND(100.0 * COUNT_IF(DECISION = 'ACCEPTED') / NULLIF(COUNT_IF(DECISION IS NOT NULL), 0), 1) ACCEPTANCE_RATE_PCT,
       ROUND(AVG(USEFULNESS_RATING), 2) AVG_USEFULNESS,
       COUNT_IF(LOOP_STAGE = 'WIN') WINS, COUNT_IF(LOOP_STAGE = 'LOSS') LOSSES,
       ROUND(100.0 * COUNT_IF(LOOP_STAGE = 'WIN') / NULLIF(COUNT_IF(LOOP_STAGE IN ('WIN','LOSS')), 0), 1) WIN_RATE_PCT,
       SUM(EXPECTED_VALUE)::NUMBER(20,2) EXPECTED_VALUE_TOTAL,
       SUM(COALESCE(REALISED_VALUE, 0))::NUMBER(20,2) REALISED_VALUE_TOTAL,
       ROUND(100.0 * SUM(COALESCE(REALISED_VALUE, 0)) / NULLIF(SUM(EXPECTED_VALUE), 0), 1) VALUE_REALISATION_PCT
FROM V_RECOMMENDATION_LOOP GROUP BY 1, 2;

SELECT 'RECOMMENDATION_FEEDBACK' t, COUNT(*) n FROM RECOMMENDATION_FEEDBACK
UNION ALL SELECT 'RECOMMENDATION_OUTCOME', COUNT(*) FROM RECOMMENDATION_OUTCOME;

SELECT STATUS, COUNT(*) n FROM AI_RECOMMENDATIONS GROUP BY 1 ORDER BY n DESC;
